apiVersion: v1
kind: Secret
metadata:
  name: {{ include "todo-app.fullname" . }}-secret
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "todo-app.labels" . | nindent 4 }}
type: Opaque
data:
  database-url: {{ .Values.secrets.databaseUrl | b64enc | quote }}
  openrouter-api-key: {{ .Values.secrets.openrouterApiKey | b64enc | quote }}
  better-auth-secret: {{ .Values.secrets.betterAuthSecret | b64enc | quote }}
  vapid-private-key: {{ .Values.secrets.vapidPrivateKey | b64enc | quote }}
  vapid-public-key: {{ .Values.secrets.vapidPublicKey | b64enc | quote }}
